### ISSUE TITLE
releases.json at test.libreelec.tv not updated anymore

### ISSUE THREAD

**Issue by dkadioglu** [LibreELEC/actions#28]
The releases.json seems to be stuck at the nightly builds from 13th of November, at least for RPi 4. Is this intended or is this an error?
I hope, this is the right place for this bug report. If not, please give me a hint, where I should report this.

**Comment by CvH** [comment]
Problem is known, gets fixed as soon spare time allows it

**Comment by dkadioglu** [comment]
Thank you very much for your reply and the clarification.
And thanks for all your work for LibreELEC!

**Comment by CvH** [comment]
tx, fixed 
https://github.com/LibreELEC/actions/pull/30
