### ISSUE TITLE
No build triggered

### ISSUE THREAD

**Issue by lomion0815** [LibreELEC/actions#33]
There where commits in libreelec.tv repository on branch release-10.0 on Jan. 7th and Jan 9th but none triggered a build of the release 10.0 nightly builds. In the action log the correct hash is shown.

**Comment by heitbaum** [comment]
These scheduled builds were cancelled as we are preparing 10.0.4

**Comment by lomion0815** [comment]
> These scheduled nightly builds were cancelled as we are preparing 10.0.4

What is the reason to cancel the nightlys? Wouldn't it be an advantage to get additional feedback/testing from us nightly users?

**Comment by heitbaum** [comment]
> > These scheduled nightly builds were cancelled as we are preparing 10.0.4
> 
> What is the reason to cancel the nightlys? Wouldn't it be an advantage to get additional feedback/testing from us nightly users?

It was a duplicate of the manual official 10.0.4 run. Aka - Less confusion and “copies of same githash - but official versus nightly”. Scheduled runs are still fully built.
